### PR TITLE
Fixed escaping in regexes using raw strings.

### LINKED ISSUE #44: invalid escape sequence in zabbix_discovery_devices
How to repeat this bug:
```bash
$ /usr/bin/zabbix_discovery_devices --config /etc/zabbix/item_zabbix_discovery_devices.json --only_rawdisk
/usr/bin/zabbix_discovery_devices:67: SyntaxWarning: invalid escape sequence '\*'
  content = re.sub('^\\s*/\*.*?\*/\\s*', '', content, 0, re.DOTALL | re.MULTILINE)
{"data": [{"{#BLOCKDEVICE}": "sdb"}, {"{#BLOCKDEVICE}": "sda"}]}
```
Occurred on environment:
```bash
$ lsb_release -d
Description:	Ubuntu 24.04 LTS
$ uname -a
Linux backup-adam.deovero.io 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ zabbix_agent2 --version
zabbix_agent2 (Zabbix) 6.4.15
Revision 09711f1760b 21 May 2024, compilation time: May 21 2024 09:44:12, built with: go1.21.3
$ python3 --version
Python 3.12.3
```

### PR DESCRIPTION
**Pull request by jeroenvermeulen**
Fixes #44.
I have only tested the `Custom - OS - Linux - Hardware` template.

### CODE REVIEW

**Comment by scoopex** [comment]
Great, thanks for your contribution!

**Comment by jeroenvermeulen** [comment]
@scoopex Any idea when this will be released?

**Comment by scoopex** [comment]
> @scoopex Any idea when this will be released?

I am really sorry - i totally missed that the ci job failed : https://github.com/zabbix-tooling/zabbix-agent-extensions/actions/runs/9260478039

The Problem was not originated in your change, it was just necessary to update to the latest zabbix release due to a incompatibility of the 6.4 zabbix agent and Ubuntu 24.04.
Now we have release 2.6.5.

**Comment by jeroenvermeulen** [comment]
Thank you @scoopex, and also thank you for the invite to collab!

**Pull request merged**
